export const tab: string
export const cell: string
export const cellActive: string
export const board: string
export const boardContent: string
export const borderFooter: string
export const button: string
export const boardCell: string
export const boarderCellActive: string
export const popup: string
